spring:
  datasource:
    url: jdbc:postgresql://helpworx.cd1w9m0fvuix.ap-northeast-2.rds.amazonaws.com:5432/dev
    username: HelpWorX
    password: successKolon!
    driver-class-name: org.postgresql.Driver
    initialization-mode : always
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: com.example.helpworx.QueryDslConfig.CustomPostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
      logging.level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace
  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true


jwt:
  header: Authorization
  secret: aGVscHdvcnhoZWxwd29yeGhlbHB3b3J4aGVscHdvcnhoZWxwd29yeGhlbHB3b3J4aGVscHdvcnhoZWxwd29yeGhlbHB3b3J4aGVscHdvcng==
  token-validity-in-seconds: 86400

